# Generated by Django 5.0.3 on 2024-03-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='weekly_goal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
